import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  ArrowLeft,
  ArrowRight,
  Award,
  Badge,
  BadgeCheck,
  Ban,
  BellRing,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  Building,
  Building2,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  ChartColumnBig,
  ChartNoAxesColumnIncreasing,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CirclePlay,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  ClipboardCopy,
  ClipboardList,
  Clock3,
  Compass,
  Crown,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  Flag,
  FolderOpen,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  Heart,
  History,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link,
  Link2,
  LockKeyhole,
  LogOut,
  LucideAngularModule,
  LucideIconData,
  Mail,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  MessageSquare,
  Network,
  Package2,
  Paperclip,
  Phone,
  Play,
  Plus,
  Podcast,
  QrCode,
  RefreshCw,
  Rocket,
  RotateCcwKey,
  Save,
  ScanQrCode,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  SquarePen,
  Star,
  StarOff,
  Tag,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserPlus,
  UserRoundPlus,
  UserX,
  Users,
  VenusAndMars,
  X
} from 'lucide-angular';

const availableIcons: Record<string, LucideIconData> = {
  ArrowLeft,
  ArrowRight,
  Award,
  Badge,
  BadgeCheck,
  Ban,
  BellRing,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  Building,
  Building2,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  ChartColumnBig,
  ChartNoAxesColumnIncreasing,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CirclePlay,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  ClipboardCopy,
  ClipboardList,
  Clock3,
  Compass,
  Crown,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  Flag,
  FolderOpen,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  Heart,
  History,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link,
  Link2,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  MessageSquare,
  Network,
  Package2,
  Paperclip,
  Phone,
  Play,
  Plus,
  Podcast,
  QrCode,
  RefreshCw,
  Rocket,
  RotateCcwKey,
  Save,
  ScanQrCode,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  SquarePen,
  Star,
  StarOff,
  Tag,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserPlus,
  UserRoundPlus,
  UserX,
  Users,
  VenusAndMars,
  X
};

const legacyIconAliases: Record<string, string> = {
  account_circle: 'CircleUser',
  add: 'Plus',
  add_business: 'BriefcaseBusiness',
  add_link: 'Link2',
  add_shopping_cart: 'ShoppingBag',
  admin_panel_settings: 'ShieldCheck',
  arrow_back: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  arrow_right: 'ArrowRight',
  attach_file: 'Paperclip',
  auto_awesome: 'Sparkles',
  badge: 'Badge',
  block: 'Ban',
  business: 'Building',
  business_center: 'BriefcaseBusiness',
  cake: 'Cake',
  calendar_today: 'CalendarDays',
  campaign: 'Megaphone',
  cancel: 'CircleX',
  category: 'LayoutGrid',
  check: 'Check',
  check_circle: 'CircleCheckBig',
  chevron_left: 'ChevronLeft',
  chevron_right: 'ChevronRight',
  close: 'X',
  cloud_upload: 'Upload',
  collections: 'Images',
  connect_without_contact: 'Handshake',
  content_copy: 'ClipboardCopy',
  dashboard: 'LayoutDashboard',
  delete: 'Trash2',
  description: 'FileText',
  done_all: 'CheckCheck',
  download: 'Download',
  edit: 'SquarePen',
  email: 'Mail',
  emoji_events: 'Trophy',
  error: 'CircleAlert',
  error_outline: 'CircleAlert',
  event: 'Calendar',
  event_available: 'CalendarCheck',
  event_busy: 'CalendarX',
  expand_less: 'ChevronUp',
  expand_more: 'ChevronDown',
  explore: 'Compass',
  favorite: 'Heart',
  flag: 'Flag',
  folder_open: 'FolderOpen',
  forum: 'MessageSquare',
  group: 'Users',
  group_add: 'UserRoundPlus',
  group_off: 'UserX',
  groups: 'Users',
  help_outline: 'CircleQuestionMark',
  history: 'History',
  history_edu: 'BookOpenText',
  image: 'Image',
  inbox: 'Inbox',
  info: 'Info',
  insights: 'ChartColumnBig',
  inventory_2: 'Package2',
  key: 'KeyRound',
  label: 'Tag',
  language: 'Languages',
  layers: 'Layers',
  lightbulb: 'Lightbulb',
  link: 'Link',
  location_city: 'Building2',
  location_on: 'MapPin',
  lock: 'LockKeyhole',
  lock_reset: 'RotateCcwKey',
  logout: 'LogOut',
  mail: 'Mail',
  manage_search: 'SearchCheck',
  menu: 'Menu',
  military_tech: 'Award',
  network_check: 'Network',
  notifications_active: 'BellRing',
  open_in_new: 'ExternalLink',
  pending_actions: 'ClipboardList',
  people: 'Users',
  person: 'User',
  person_add: 'UserPlus',
  person_off: 'UserX',
  phone: 'Phone',
  picture_as_pdf: 'FileText',
  place: 'MapPinned',
  play_arrow: 'Play',
  play_circle: 'CirclePlay',
  podcasts: 'Podcast',
  psychology: 'Brain',
  public: 'Globe',
  publish: 'Upload',
  qr_code_2: 'QrCode',
  qr_code_scanner: 'ScanQrCode',
  refresh: 'RefreshCw',
  rocket_launch: 'Rocket',
  save: 'Save',
  schedule: 'Clock3',
  school: 'GraduationCap',
  search: 'Search',
  search_off: 'SearchX',
  security: 'Shield',
  send: 'Send',
  share: 'Share2',
  shield: 'Shield',
  shopping_bag: 'ShoppingBag',
  star: 'Star',
  star_border: 'StarOff',
  sync: 'RefreshCw',
  thumb_up: 'ThumbsUp',
  timelapse: 'Timer',
  timeline: 'ChartNoAxesColumnIncreasing',
  tips_and_updates: 'Sparkles',
  trending_up: 'TrendingUp',
  update: 'RefreshCw',
  upcoming: 'CalendarPlus',
  upload_file: 'FileUp',
  verified: 'BadgeCheck',
  visibility: 'Eye',
  visibility_off: 'EyeOff',
  waving_hand: 'Hand',
  wc: 'VenusAndMars',
  work: 'BriefcaseBusiness',
  work_outline: 'BriefcaseBusiness',
  workspace_premium: 'Crown'
};

function toLucideKey(name: string): string {
  return name
    .split(/[_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function resolveIcon(name: string): LucideIconData {
  const normalized = name.trim();
  if (!normalized) {
    return CircleQuestionMark;
  }

  const iconKey = legacyIconAliases[normalized] ?? toLucideKey(normalized);
  return availableIcons[iconKey] ?? CircleQuestionMark;
}

@Component({
  selector: 'ui-icon',
  imports: [LucideAngularModule],
  template: `<i-lucide [img]="icon()" [size]="size()" [strokeWidth]="strokeWidth()" class="inline-block align-middle" />`,
  host: {
    class: 'inline-flex shrink-0 align-middle leading-none',
    'aria-hidden': 'true'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconComponent {
  readonly name = input('');
  readonly size = input('1em');
  readonly strokeWidth = input(2);

  protected readonly icon = computed(() => resolveIcon(this.name()));
}
